"""initial tables

Revision ID: b7b484f3ed2a
Revises:
Create Date: 2026-06-02 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7b484f3ed2a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Users table
    op.create_table('users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('hashed_password', sa.String(length=255), nullable=False),
        sa.Column('role', sa.String(length=50), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('two_factor_secret', sa.String(length=32), nullable=True),
        sa.Column('two_factor_enabled', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)

    # Refresh tokens table
    op.create_table('refresh_tokens',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('token', sa.String(length=500), nullable=False),
        sa.Column('expires_at', sa.DateTime(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)

    # Odeljenja table
    op.create_table('odeljenja',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('naziv', sa.String(length=200), nullable=False),
        sa.Column('opis', sa.Text(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('naziv')
    )
    op.create_index(op.f('ix_odeljenja_id'), 'odeljenja', ['id'], unique=False)

    # Strucne spreme table
    op.create_table('strucne_spreme',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('naziv', sa.String(length=200), nullable=False),
        sa.Column('nivo', sa.Integer(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('naziv')
    )
    op.create_index(op.f('ix_strucne_spreme_id'), 'strucne_spreme', ['id'], unique=False)

    # Radna mesta table
    op.create_table('radna_mesta',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('naziv', sa.String(length=200), nullable=False),
        sa.Column('opis', sa.Text(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('naziv')
    )
    op.create_index(op.f('ix_radna_mesta_id'), 'radna_mesta', ['id'], unique=False)

    # Members table
    op.create_table('members',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('ime', sa.String(length=100), nullable=False),
        sa.Column('prezime', sa.String(length=100), nullable=False),
        sa.Column('jmbg', sa.String(length=13), nullable=True),
        sa.Column('email', sa.String(length=255), nullable=True),
        sa.Column('telefon', sa.String(length=20), nullable=True),
        sa.Column('adresa', sa.String(length=255), nullable=True),
        sa.Column('datum_rodjenja', sa.DateTime(), nullable=True),
        sa.Column('strucna_sprema_id', sa.Integer(), nullable=True),
        sa.Column('radno_mesto_id', sa.Integer(), nullable=True),
        sa.Column('odeljenje_id', sa.Integer(), nullable=True),
        sa.Column('datum_uclanjenja', sa.DateTime(), nullable=True),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['odeljenje_id'], ['odeljenja.id'], ),
        sa.ForeignKeyConstraint(['radno_mesto_id'], ['radna_mesta.id'], ),
        sa.ForeignKeyConstraint(['strucna_sprema_id'], ['strucne_spreme.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('jmbg')
    )
    op.create_index(op.f('ix_members_email'), 'members', ['email'], unique=False)
    op.create_index(op.f('ix_members_id'), 'members', ['id'], unique=False)
    op.create_index(op.f('ix_members_ime'), 'members', ['ime'], unique=False)
    op.create_index(op.f('ix_members_prezime'), 'members', ['prezime'], unique=False)
    op.create_index(op.f('ix_members_status'), 'members', ['status'], unique=False)

    # Clanarine table
    op.create_table('clanarine',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('member_id', sa.Integer(), nullable=False),
        sa.Column('iznos', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('valuta', sa.String(length=3), nullable=True),
        sa.Column('period_od', sa.DateTime(), nullable=False),
        sa.Column('period_do', sa.DateTime(), nullable=False),
        sa.Column('datum_uplate', sa.DateTime(), nullable=True),
        sa.Column('nacin_placanja', sa.String(length=50), nullable=True),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('broj_uplatnice', sa.String(length=100), nullable=True),
        sa.Column('napomena', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clanarine_id'), 'clanarine', ['id'], unique=False)
    op.create_index(op.f('ix_clanarine_member_id'), 'clanarine', ['member_id'], unique=False)
    op.create_index(op.f('ix_clanarine_status'), 'clanarine', ['status'], unique=False)

    # Edukacije table
    op.create_table('edukacije',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('naziv', sa.String(length=300), nullable=False),
        sa.Column('opis', sa.Text(), nullable=True),
        sa.Column('tip', sa.String(length=50), nullable=True),
        sa.Column('datum_pocetka', sa.DateTime(), nullable=False),
        sa.Column('datum_zavrsetka', sa.DateTime(), nullable=True),
        sa.Column('trajanje_sati', sa.Integer(), nullable=True),
        sa.Column('lokacija', sa.String(length=255), nullable=True),
        sa.Column('max_polaznika', sa.Integer(), nullable=True),
        sa.Column('cena', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('bodovi', sa.Integer(), nullable=True),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_edukacije_id'), 'edukacije', ['id'], unique=False)

    # Prijave edukacija table
    op.create_table('prijave_edukacija',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('edukacija_id', sa.Integer(), nullable=False),
        sa.Column('member_id', sa.Integer(), nullable=False),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('prisustvo', sa.Boolean(), nullable=True),
        sa.Column('ocena', sa.Integer(), nullable=True),
        sa.Column('sertifikat_izdat', sa.Boolean(), nullable=True),
        sa.Column('datum_prijave', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['edukacija_id'], ['edukacije.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prijave_edukacija_edukacija_id'), 'prijave_edukacija', ['edukacija_id'], unique=False)
    op.create_index(op.f('ix_prijave_edukacija_id'), 'prijave_edukacija', ['id'], unique=False)
    op.create_index(op.f('ix_prijave_edukacija_member_id'), 'prijave_edukacija', ['member_id'], unique=False)

    # Sertifikati table
    op.create_table('sertifikati',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('prijava_id', sa.Integer(), nullable=False),
        sa.Column('broj', sa.String(length=100), nullable=False),
        sa.Column('datum_izdavanja', sa.DateTime(), nullable=True),
        sa.Column('pdf_path', sa.String(length=500), nullable=True),
        sa.ForeignKeyConstraint(['prijava_id'], ['prijave_edukacija.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('broj'),
        sa.UniqueConstraint('prijava_id')
    )
    op.create_index(op.f('ix_sertifikati_id'), 'sertifikati', ['id'], unique=False)

    # Kategorije table
    op.create_table('kategorije',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('naziv', sa.String(length=200), nullable=False),
        sa.Column('parent_id', sa.Integer(), nullable=True),
        sa.Column('opis', sa.Text(), nullable=True),
        sa.Column('sort_order', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['parent_id'], ['kategorije.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kategorije_id'), 'kategorije', ['id'], unique=False)

    # Tags table
    op.create_table('tags',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('naziv', sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('naziv')
    )
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)

    # Dokumenti table
    op.create_table('dokumenti',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('naslov', sa.String(length=300), nullable=False),
        sa.Column('sadrzaj', sa.Text(), nullable=True),
        sa.Column('kategorija_id', sa.Integer(), nullable=True),
        sa.Column('author_id', sa.Integer(), nullable=True),
        sa.Column('file_path', sa.String(length=500), nullable=True),
        sa.Column('file_type', sa.String(length=50), nullable=True),
        sa.Column('file_size', sa.Integer(), nullable=True),
        sa.Column('version', sa.Integer(), nullable=True),
        sa.Column('is_published', sa.Boolean(), nullable=True),
        sa.Column('view_count', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['kategorija_id'], ['kategorije.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dokumenti_id'), 'dokumenti', ['id'], unique=False)
    op.create_index(op.f('ix_dokumenti_kategorija_id'), 'dokumenti', ['kategorija_id'], unique=False)
    op.create_index(op.f('ix_dokumenti_naslov'), 'dokumenti', ['naslov'], unique=False)

    # Document tags table
    op.create_table('document_tags',
        sa.Column('document_id', sa.Integer(), nullable=False),
        sa.Column('tag_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['document_id'], ['dokumenti.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('document_id', 'tag_id')
    )

    # Email templates table
    op.create_table('email_templates',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('subject', sa.String(length=300), nullable=False),
        sa.Column('body_html', sa.Text(), nullable=False),
        sa.Column('body_text', sa.Text(), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('variables', sa.Text(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_email_templates_id'), 'email_templates', ['id'], unique=False)

    # Email logs table
    op.create_table('email_logs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('recipient', sa.String(length=255), nullable=False),
        sa.Column('template_id', sa.Integer(), nullable=True),
        sa.Column('subject', sa.String(length=300), nullable=False),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('sent_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['template_id'], ['email_templates.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_logs_id'), 'email_logs', ['id'], unique=False)
    op.create_index(op.f('ix_email_logs_recipient'), 'email_logs', ['recipient'], unique=False)

    # Notifications table
    op.create_table('notifications',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('type', sa.String(length=50), nullable=False),
        sa.Column('title', sa.String(length=300), nullable=False),
        sa.Column('message', sa.Text(), nullable=True),
        sa.Column('link', sa.String(length=500), nullable=True),
        sa.Column('is_read', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)

    # Audit log table
    op.create_table('audit_log',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('action', sa.String(length=100), nullable=False),
        sa.Column('resource', sa.String(length=100), nullable=False),
        sa.Column('resource_id', sa.Integer(), nullable=True),
        sa.Column('details', sa.Text(), nullable=True),
        sa.Column('ip_address', sa.String(length=45), nullable=True),
        sa.Column('user_agent', sa.String(length=500), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_id'), 'audit_log', ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_log')
    op.drop_table('notifications')
    op.drop_table('email_logs')
    op.drop_table('email_templates')
    op.drop_table('document_tags')
    op.drop_table('dokumenti')
    op.drop_table('tags')
    op.drop_table('kategorije')
    op.drop_table('sertifikati')
    op.drop_table('prijave_edukacija')
    op.drop_table('edukacije')
    op.drop_table('clanarine')
    op.drop_table('members')
    op.drop_table('radna_mesta')
    op.drop_table('strucne_spreme')
    op.drop_table('odeljenja')
    op.drop_table('refresh_tokens')
    op.drop_table('users')
    # ### end Alembic commands ###
